---
name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    environment:
      name: ghcr
      url: https://ghcr.io/zachspar/fred-mcp/fred-mcp-server
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/zachspar/fred-mcp/fred-mcp-server:latest
            ghcr.io/zachspar/fred-mcp/fred-mcp-server:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/p/fred-mcp
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

